### PR TITLE
Update Godot to 3.5.1

### PR DESCRIPTION
**Pull request by TuxTheAstronaut**

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
You need to update the AppStream metadata XML file as done in https://github.com/flathub/org.godotengine.Godot/commit/08b84bc288b34c98700e8bd38c03caa5e0467cc2. This is done by adding a line for the `3.5.1` release at the top of the releases list. The release date should be set to the date 3.5.1 was released (`2022-09-28`).

**Comment by TuxTheAstronaut** [comment]
Updated the XML and added 3.5.1 to the release

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Comment by Calinou** [comment]
bot, build

**Pull request merged**
