### PR TITLE
Bump the runtime to 22.08

### PR DESCRIPTION
**Pull request by farribeiro**
btw... I think needs to update de extension version

### CODE REVIEW

**Comment by farribeiro** [comment]
bot, build

**Comment by farribeiro** [comment]
@Calinou Created 22.08 branch for openjdk...

**Comment by farribeiro** [comment]
The Godot Tools fails with this freedesktop

**Comment by xarses** [comment]
```
Traceback (most recent call last):
  File "/app/bin/scons", line 33, in <module>
    sys.exit(load_entry_point('SCons==4.4.0', 'console_scripts', 'scons')())
  File "/app/bin/scons", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for SCons
```

The problems appears to be that neither SCons 4.3.0 and 4.4.0 are ready to use python3.10 (which is packed in 22.08 of the SDK) instead of python3.9 (packed in 21.08) The metadata failing This appears to be one of many deprecations that was finally removed in 3.10

**Comment by Calinou** [comment]
In the meantime, could [Pyston](https://github.com/pyston/pyston) be used to run SCons instead? This would also speed up building a little.

**Comment by Calinou** [comment]
Superseded by https://github.com/flathub/org.godotengine.Godot/pull/114. Thanks for the contribution nonetheless!

**Pull request closed without merging**
