### PR TITLE
Update Godot to 4.0.2

### PR DESCRIPTION
**Pull request by Zishan-Rahman**

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works. Thanks!

**Review by Calinou — CHANGES_REQUESTED** [review]
Before this can be merged, AppStream metadata needs to be modified to include 4.0.2 and its release date (`2023-04-04`): https://github.com/flathub/org.godotengine.Godot/blob/master/org.godotengine.Godot.appdata.xml#L49

**Comment by Zishan-Rahman** [comment]
@Calinou Just did that now. Sorry for not doing it earlier, I somehow missed it :man_facepalming: 

Once the new build passes, we should be able to merge this PR. How do I denote here that the changes needed for merging have now been addressed (or is it you who does that)?

**Review by reisaraujo-miguel — COMMENTED** [review]
You added the version as `4.0.1` instead of `4.0.2`

**Comment by reisaraujo-miguel** [comment]
> You added the version as `4.0.1` instead of `4.0.2`

Oh, you just fixed that ksksksksk

**Comment by Zishan-Rahman** [comment]
> > You added the version as `4.0.1` instead of `4.0.2`
> 
> Oh, you just fixed that ksksksksk

@reisaraujo-miguel No worries hahahah :laughing:

The ongoing build should succeed now :+1:

**Comment by Zishan-Rahman** [comment]
@Calinou it's been about 3 days since I've [made the changes you've requested](https://github.com/flathub/org.godotengine.Godot/pull/123/files#diff-e62a8900017f7c5779ee5dc5471baec9be420701f27744dba096d9bb5fb26ab2). I still have no idea how to denote that they've been accounted for.

If you could review, then approve and merge this PR as soon as possible, I'll very much appreciate it :+1:

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
