### PR TITLE
.NET 7 Support

### LINKED ISSUE #8: Build mono module
Build with `module_mono_enabled=yes`. This currently fails trying to find `monosgen-2` module.

### PR DESCRIPTION
**Pull request by CharlieQLe**
This is still unfinished, since I still need to figure out a location for the local nuget source that contains `Godot-SDK`. Other than that, I expect this to work fine, but I have not yet tested a build. Once completed, this should fix #8 .

### CODE REVIEW

**Comment by CharlieQLe** [comment]
I've identified a problem with the current build process where on trying to restore the projects after generating the glue and the final Godot binary, `Godot.SourceGenerators.Internal.csproj` and `GodotSharp.csproj` will fail to be restored- `error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.`

**Comment by CharlieQLe** [comment]
As of now, the Flatpak for Godot 4 with .NET 6 is up and running. However, the Godot-SDK Nuget package is not exported to anywhere under the user's home directory. Without it, the Flatpak of VSCode does not properly handle any of Godot's C# objects. Once it is properly exported, users would need to manually add the Nuget source and ensure that VSCode or whatever IDE they use detects the dotnet6 extension.

**Comment by CharlieQLe** [comment]
@Calinou with Godot 4.0 beta 1 out today, I think this should be ready to be merged into the beta branch if this next build is successful. The only caveat would be adding the local Nuget source, at least until Godot.NET.Sdk gets uploaded.

**Comment by DomiStyle** [comment]
Not sure if this is the correct place to report this issue, but installing the Flatpak package for Godot with .NET 6 breaks .NET 6 for every other Flatpak with this error message:

```
/home/domi/Documents/git/test/test.csproj : error NU1301: The local source '/home/domi/.var/app/org.godotengine.Godot/data/godot/mono/GodotNuGetFallbackFolder' doesn't exist.
```

To reproduce simply install this package as well as Visual Studio Code in Flatpak. Try to build a project in VS Code and you will be met with this error message because VS Code cannot access the Godot files (obviously).

Deleting `~/.nuget/NuGet/config/Godot.Offline.config` resolves this problem but it gets recreated every time Godot loads a project.

Unrelated to this it seems like Godot in a Flatpak is significantly slower and also renders black in some areas while it is loading:
Screenshot from 2022-09-29 22-53-16

**Comment by CharlieQLe** [comment]
> Not sure if this is the correct place to report this issue, but installing the Flatpak package for Godot with .NET 6 breaks .NET 6 for every other Flatpak with this error message:
> 
> ```
> /home/domi/Documents/git/test/test.csproj : error NU1301: The local source '/home/domi/.var/app/org.godotengine.Godot/data/godot/mono/GodotNuGetFallbackFolder' doesn't exist.
> ```
> 
> To reproduce simply install this package as well as Visual Studio Code in Flatpak. Try to build a project in VS Code and you will be met with this error message because VS Code cannot access the Godot files (obviously).
> 
> Deleting `~/.nuget/NuGet/config/Godot.Offline.config` resolves this problem but it gets recreated every time Godot loads a project.

The solution is to add a filesystem override.
```
flatpak --user overrides --filesystem=~/.var/app/org.godotengine.Godot/data/godot/mono/GodotNuGetFallbackFolder
```
Long term, this solution as well as the commands needed to added the nuget source are not ideal. [Here](https://github.com/godotengine/godot/pull/65507#issuecomment-1242590456), it is mentioned that the fallback folder will eventually be removed when the Nuget packages are available on nuget.org. Despite the availability of the beta 2 nuget packages, it seems that building the flatpak at the moment creates nuget packages that are of version dev8, not beta2, and the solutions reference dev8. If the beta2 nuget packages can be built, then the local source won't need to be added, and this fallback may no longer need an override I hope.

> Unrelated to this it seems like Godot in a Flatpak is significantly slower and also renders black in some areas while it is loading: Screenshot from 2022-09-29 22-53-16

Are you running on Wayland or X11? What GPU are you running on? I have a 6700xt and I run Godot 4 on Wayland and run into the same black screen, so it would be useful to know if this is a problem with the flatpak or drivers. The slowdown is likely due to a regression, issue #108 does mention this.

**Comment by DomiStyle** [comment]
> The solution I imagine is to add a filesystem override.

That seems more like a workaround than a solution but if it will be resolved once the packages are on Nuget.org I guess it is fine for now. .NET 6 support is really new after all. :)

> Are you running on Wayland or X11? What GPU are you running on?

Wayland on an 6900 XT but I'm fairly certain I had the same issue a while ago on X11.

> The slowdown is likely due to a regression, issue https://github.com/flathub/org.godotengine.Godot/issues/108 does mention this.

Interesting, will do some testing once I have some spare time.

**Comment by DomiStyle** [comment]
Did some more testing with the Flatpak.

It seems like both the black window and longer loading are present in the regular Godot 4 builds as well, so not an issue with the Flatpak.

Did find one that only happens in the Flatpak though, OpenXR does not work and fails with the following message when the game starts:

```
E 0:00:00:0011   load_supported_extensions: OpenXR: Failed to enumerate number of extension properties
  <C++ Error>    Condition "((result) < 0)" is true. Returning: false
  <C++ Source>   modules/openxr/openxr_api.cpp:152 @ load_supported_extensions()
```

Not sure yet what is missing but no issues on the official builds.

**Comment by A6GibKm** [comment]
Bot, build

**Comment by A6GibKm** [comment]
bot, build

**Comment by waffshappen** [comment]
> Build [25576 successful](https://buildbot.flathub.org/#/builders/6/builds/25576) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/8235/org.godotengine.Godot.flatpakref
> ```

The output is not available anymore (404) - could this be rebuilt?

**Comment by snoweuph** [comment]
> Build [54325 successful](https://buildbot.flathub.org/#/builders/6/builds/54325) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/36970/org.godotengine.Godot.flatpakref
> ```

This is not available anymore 404 :sob:

**Comment by CharlieQLe** [comment]
I'm not really interested in maintaining this PR at the moment for a variety of reasons. Between long build times and the lack of version management (an equivalent to Unity Hub really), I don't really like running the engine itself as a Flatpak. Once Godot eventually unifies the C# and non-C# builds, I will probably come back to finish this PR, but that could be a long time from now.

If anyone needs C# support now, I would recommend something like my [Godots Flatpak](https://github.com/CharlieQLe/io.github.MakovWait.Godots) if C# support is something you do need, as it aggregates both non-C# and C# builds of Godot, as well as multiple different versions. Or run a container with Godot and .NET in it, and use Visual Studio Code's Dev Container extension to connect to it.

**Comment by Zishan-Rahman** [comment]
> I'm not really interested in maintaining this PR at the moment for a variety of reasons. Between long build times and the lack of version management (an equivalent to Unity Hub really), I don't really like running the engine itself as a Flatpak. Once Godot eventually unifies the C# and non-C# builds, I will probably come back to finish this PR, but that could be a long time from now.
> 
> If anyone needs C# support now, I would recommend something like my [Godots Flatpak](https://github.com/CharlieQLe/io.github.MakovWait.Godots) if C# support is something you do need, as it aggregates both non-C# and C# builds of Godot, as well as multiple different versions. Or run a container with Godot and .NET in it, and use Visual Studio Code's Dev Container extension to connect to it.

I was actually considering reorganising the commits in your PR by copying them to my fork of [the Flathub repository used for submitting new Flatpaks](https://github.com/flathub/flathub), so that the C# builds (both 3 and 4) could, potentially, go up on Flathub as separate Flatpaks, so that those who need them can still install them. I personally think it's better to include the C# builds on Flathub separately from the standard builds as Calinou suggested, at least until the C# and non-C# builds finally get unified. I'd just like to request your permission to do so (from both you and Calinou), and when I _do_ get round to it (if I have your permission, of course), I'll make sure to let you and Calinou know here when I've opened those PRs. [I managed to get the standard Godot 3 build uploaded to Flathub](https://github.com/flathub/flathub#3988), so I have _a little bit_ of experience with getting new Flatpaks up on Flathub. I'll also need to create a PR for [flatpak-builder-lint](https://github.com/flathub/flatpak-builder-lint) so that support for external code editors can be retained for both Flatpaks.

@CharlieQLe @Calinou sorry for the pings. Please can you let me know if you think what I'm suggesting here is a good idea and whether or not I should action it? I'd appreciate any advice you both have.

Also, Charlie, your Godots Flatpak could potentially _also_ go up on Flathub, in my humble opinion. I didn't even know a Godot version manager even existed until now!

**Comment by CharlieQLe** [comment]
@Zishan-Rahman Go for it! A separate C# flatpak would be a good thing to see for people just getting into Godot that need a Flatpak, though it should be noted that the custom dotnet editors isn't supported afaik.

**Comment by Zishan-Rahman** [comment]
@CharlieQLe @Calinou Sorry for the pings and for the late reply to Charlie's comment. I just set up PRs on [Flathub's new app submission repo](https://github.com/flathub/flathub) for versions of Godot 3 and Godot 4 with .NET support. Godot 4's .NET version _should_ be easy enough, since that's what the latest revisions in Charlie's PR were based on anyway. Godot **3**'s .NET version l'll likely need some help with to make sure everything works, since I'm not very familiar with the .NET and Mono ecosystems at the moment.

I have therefore set up [a repo of my own](https://github.com/Zishan-Rahman/godot3-mono-flatpak) using commit histories from this PR and the Godot 3 Flatpak, and I have sent both of you collaboration invites so that you can help if and when you can. Each time a change is pushed there, I'll push that change to the branch in my fork of [flathub/flathub](https://github.com/flathub/flathub) used for the Godot 3 .NET Flatpak build. I'll appreciate it a lot if you could please accept these invites as soon as possible, so that we can fix any issues and hopefully get these Flatpaks submitted to Flathub as soon as possible.

Here's the Godot 4 PR: flathub/flathub#4594
Here's the Godot 3 PR: flathub/flathub#4595

**Comment by Zishan-Rahman** [comment]
@CharlieQLe @Calinou (sorry for the pings) It took a while, but we _finally_ got the C# Godot 4 build on Flathub: https://flathub.org/apps/org.godotengine.GodotSharp

Godot 3's C# Flatpak is still a work-in-progress as of now, but for Godot 4's C# build, it _looks_ like we can close this PR. @CharlieQLe Thanks for all your hard work in setting this up and continuing to maintain it until now! I don't know if you've been invited to maintain [the new Flatpak](https://github.com/flathub/org.godotengine.GodotSharp) as a collaborator, so if you haven't, we could always create an issue on [the flathub/flathub repository](https://github.com/flathub/flathub) to have you added as one.

**Comment by Calinou** [comment]
Closing per the above comment. Thanks a ton for the contribution :slightly_smiling_face:

**Pull request closed without merging**
