### PR TITLE
Update to 3.1 stable

### PR DESCRIPTION
**Pull request by Pobega**

### CODE REVIEW

**Comment by Pobega** [comment]
I'm not sure of the status of your `beta` branch going into `master`, so I'm opening this PR against the beta branch.

**Comment by Pobega** [comment]
The Flatpak seems to run fine for me. Converted a few old games from 3.0.6 to 3.1 and everything seems to work as expected.

I did notice that the version was still listed as `3.1 rc2` so I updated that as well.

**Comment by Pobega** [comment]
I do get a few new errors on the command line when exiting (via the GUI), I'm unsure if this is expected behavior:

```WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2092.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```

**Comment by Calinou** [comment]
I have some changes to add on top of this, but this can be merged as-is; I'll continue my work later. :+1:

**Comment by Pobega** [comment]
@Calinou do you have merge powers? I see from previous PRs that Alex is busy man

**Comment by Calinou** [comment]
@Pobega I do!

Thanks for your contribution :smiley:

**Pull request merged**
