### PR TITLE
Update Godot to 4.3-beta3 for Flathub Beta

### PR DESCRIPTION
**Pull request by Zishan-Rahman**

### CODE REVIEW

**Comment by Zishan-Rahman** [comment]
@wjt Sorry for the ping, but it appears that the changes you made for https://github.com/flathub/org.godotengine.Godot/pull/170 are now generating a linter error that is effectively stopping this PR's test build from succeeding: `finish-args-contains-both-x11-and-wayland`. I don't know exactly _when_ this was enforced, but I _do_ know that this wasn't an issue when you opened your PR and it got merged.

Usually, the right fix would be to rewrite `--socket=x11` in `finish-args` as `--socket=fallback-x11`, but [as you said in your PR](https://github.com/flathub/org.godotengine.Godot/pull/170#issue-2337892345), there is a perfectly valid reason _why_ you _didn't_ do that:

> Godot 4.3 adds opt-in Wayland support. To use this, the Wayland socket is of course needed.
> 
> **--socket=x11 is left as-is rather than being replaced with fallback-x11 because X11 remains the default; manual intervention is needed to configure the editor and/or game to use Wayland.**

So we need to either (1) take out `--socket=wayland` from `finish-args`, effectively undoing the changes you made in your PR, or (2) grant this Flatpak an exception to this error so that both of the `socket` `finish-args` can be kept, which _is_ possible through opening a PR for [flatpak-builder-lint]( https://github.com/flathub-infra/flatpak-builder-lint), as it already does for `talk-name=org.freedesktop.Flatpak`.

I'd like your opinion on what to do before I commit to a final decision, so please let me know what you think we should do at your earliest opportunity. I look forward to your advice.

**Comment by wjt** [comment]
I suggest option 2.

**Comment by Zishan-Rahman** [comment]
> I suggest option 2.

@wjt (sorry for the ping) Thanks for your suggestion. I opened a flatpak-builder-lint PR here: https://github.com/flathub-infra/flatpak-builder-lint/pull/433

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
@Calinou looks like this PR can finally be merged now :+1:

**Pull request merged**
